### ISSUE TITLE
Support both QC and Hedgehog?

### ISSUE THREAD

**Issue by moodmosaic** [FuzzyMonkeyCo/monkey#64]
Is it possible to use this service but instead of QuickCheck (QC) use Hedgehog? There's even a way to [use QC generators in Hedgehog and vice versa](https://hackage.haskell.org/package/hedgehog-quickcheck). 

@jystic shows how a bug slipped in [bos/text](https://github.com/bos/text) library by using QC default arbitraries. It's on [this](https://youtu.be/AIv_9T0xKEo?t=710) video at 11:50 (up to 13:09). 

The solution would be to use Hedgehog's `Range` type, which offers fine-grained control over the scope and shrinking of generated values.

Being able to support both QC and Hedgehog may actually be very interesting.

**Comment by fenollp** [comment]
Hi @moodmosaic! Thanks for taking interest in this project!

This is a great suggestion and in fact `monkey`’s backend is designed such that different frameworks and languages can be used / experimented upon. The whole idea is to build a sustainable product that can move forward the (bad) state of software around the world...

Today there’s only one such backend. It’s written in Erlang and uses what the speaker in your link calls Integrated Shrinking. 

Sorry to have taken so long to reply, it seems I didn’t get the notification somehow. 
If you’d like to discuss some more or are looking for contract work feel free to contact me directly, I’d be thrilled :)
